# Generated by Django 2.0.7 on 2018-08-06 14:44

import ckeditor_uploader.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('subTitle', models.CharField(blank=True, max_length=80, null=True, verbose_name='SubTitle')),
                ('Image', models.ImageField(upload_to='Profile/', verbose_name='Image')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Start')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
