# Generated by Django 2.1 on 2018-09-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180903_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Checked'),
        ),
    ]
