# Generated by Django 2.1 on 2018-09-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contact_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Image',
            new_name='image',
        ),
    ]
