# Generated by Django 2.2.1 on 2019-05-11 14:25

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('app', '0006_auto_20180905_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('subTitle', models.CharField(blank=True, max_length=80, null=True, verbose_name='SubTitle')),
                ('image', models.ImageField(upload_to='Portfolio/', verbose_name='Image')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Start')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End')),
                ('content', models.TextField(verbose_name='Content')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
                'ordering': ['-updated', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
