# Generated by Django 2.0.7 on 2018-08-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
