# Generated by Django 2.1 on 2018-08-12 17:33

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.upload_path, verbose_name='Attach File'),
        ),
    ]
