# Generated by Django 2.1 on 2018-08-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180814_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['timestamp'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
