# Generated by Django 2.1 on 2018-08-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180815_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish', 'title'], 'verbose_name': 'post', 'verbose_name_plural': 'post'},
        ),
    ]
