# Generated by Django 2.1 on 2018-08-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.TextField(blank=True, null=True, verbose_name='Activation Key'),
        ),
    ]
