# Generated by Django 2.1 on 2018-08-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_activation_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_key',
        ),
    ]
